### ISSUE TITLE
Changing the Broadcast Rate

### ISSUE THREAD

**Issue by ghost** [happyzleaf/PixelGenocide#11]
The placeholder `%pixelgenocide_timer_human%` breaks everytime I change the broadcast rate. I am creating a GUI with VirtualChest that shows the countdown before the next pokémon genocide. Is there something I am doing wrong or?

> **Before Changing:**
![2020-04-23_21 39 22](https://user-images.githubusercontent.com/36751580/80175891-c8069d80-85ab-11ea-9a56-216ab81405f9.png)
![2020-04-23_21 39 25](https://user-images.githubusercontent.com/36751580/80175895-ca68f780-85ab-11ea-92b8-5057d25b2f85.png)

> **After Changing + Restart:**
![2020-04-23_21 42 04](https://user-images.githubusercontent.com/36751580/80175913-db196d80-85ab-11ea-8c7e-3dcc7ba65265.png)

**Comment by ghost** [comment]
I figured it out, the broadcast cannot have any kind of negative number in its rate or else it will error and not produce any broadcasts.

**Comment by happyzleaf** [comment]
I’m currently in a heavy study session so I don’t have much spare time. I’ll take a look next time I’m free and let you know.

On 24 Apr 2020, at 06:47, zaxis <notifications@github.com<mailto:notifications@github.com>> wrote:


The placeholder %pixelgenocide_timer_human% breaks everytime I change the broadcast rate. I am creating a GUI with VirtualChest that shows the countdown before the next pokémon genocide. Is there something I am doing wrong or?

Before Changing:
[2020-04-23_21 39 22]<https://user-images.githubusercontent.com/36751580/80175891-c8069d80-85ab-11ea-9a56-216ab81405f9.png>
[2020-04-23_21 39 25]<https://user-images.githubusercontent.com/36751580/80175895-ca68f780-85ab-11ea-92b8-5057d25b2f85.png>

After Changing + Restart:
[2020-04-23_21 42 04]<https://user-images.githubusercontent.com/36751580/80175913-db196d80-85ab-11ea-8c7e-3dcc7ba65265.png>
