### ISSUE TITLE
Better countdown

### ISSUE THREAD

**Issue by Mrkele** [happyzleaf/PixelGenocide#4]
Can I add a clear countdown?
Add lang file

**Comment by hqppyz** [comment]
Also tip for me: add a "silent" option

**Comment by SnowBlitzz** [comment]
Would love to see this.

**Comment by hqppyz** [comment]
Forgot to mention this issue in this commit
https://github.com/happyzleaf/PixelGenocide/commit/d5416fca83386e415771246be703a04293b36a49

**Comment by hqppyz** [comment]
Okay looks to be fine
