### ISSUE TITLE
Pixelmon Genocide v1.0.3 || Clears legends, shinies, bosses

### ISSUE THREAD

**Issue by Coolkc456** [happyzleaf/PixelGenocide#6]
Hello, in the config I set legends, shinies, and bosses to false so that they are not "removed regardless of their specs" yet they are still cleared upon the plugin purging pokemon.
Here is my config: https://pastebin.com/eLbBzhS3

Am I doing something wrong or missing anything? Thanks in advance.

**Comment by EverNife** [comment]
![image](https://user-images.githubusercontent.com/11357801/46276504-af9ce100-c536-11e8-831e-a02e03801063.png)

For example:

Keep.Boses = (true, i want to keep them)
Keep.Shinies = (true, i want them as well)
Keep.Legendaries (false, i dont think i want legendaries)


In your config, you are not keeping anything.

**Comment by hqppyz** [comment]
As stated by evernife, you're doing it in the opposite way. Closing.
