### ISSUE TITLE
Whitelist all Pokemon

### ISSUE THREAD

**Issue by gustavogsimas** [happyzleaf/PixelGenocide#9]
Hello,

Maybe I didn't understand how this works, but is there a way to whitelist all pokemon besides those on the blacklist? Or do I have to put manually all the names of the 800 pokemon on the whitelist?

Thank you

**Comment by hqppyz** [comment]
No, I've added both the whitelist *and* the blacklist to prevent anything like that. If a pokémon is in the whitelist then it's going to be kept regardless of anything else, while if it's in the blacklist then it's gonna be wiped regardless of anything else.

**Comment by hqppyz** [comment]
Closing since it's not an issue, feel free to reopen if anything's actually broken, while for general support you might want to contact me over discord (look into my github profile to get my id) or over the pixelmon server admin's discord.
